### ISSUE TITLE
4 missing prerequisites ... yet PASS

### ISSUE THREAD

**Issue by jkeenan** [rjbs/Git-BranchManager#1]
Today, in light of reading [*my git branch manager*](https://rjbs.manxome.org/rubric/entry/2122), I downloaded this repository's code and began to explore it.  I got the following output (trimmed):
```
[Git-BranchManager] 530 $ dzil test
...
Checking if your kit is complete...
Looks good
Warning: prerequisite JSON 0 not found.
Warning: prerequisite Process::Status 0 not found.
Warning: prerequisite Text::Table 0 not found.
...
# 
# *** WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING ***
# 
# The following REQUIRED prerequisites were not satisfied:
# 
# JSON is not installed (any version required)
# Process::Status is not installed (any version required)
# Text::Table is not installed (any version required)
# Test::Pod is not installed (version '1.41' required)
# 
t/00-report-prereqs.t .. ok   
All tests successful.
Files=1, Tests=1,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.14 cusr  0.00 csys =  0.16 CPU)
Result: PASS
[DZ] all's well; removing .build/v3HkoLMFM5
```
So there were 4 prerequisites not found ... yet the result was `PASS`.  That seems contradictory.

**Comment by rjbs** [comment]
t/00-report-prereqs is only meant to report the prereqs, not bass/fail based on them.  Any CPAN installer would install them before running.  The usual thing here would be for a developer to run `dzil listdeps --missing | cpanm`
